export const REGISER_LOADING = 'REGISTER_LOADING';
export const REGISER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';
